manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/AlexGirardDev
  projects:
    - name: zmk
      remote: AlexGirardDev
      revision: main
      import: app/west.yml
  self:
    path: config
