manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: AlexGirardDev
      url-base: https://github.com/AlexGirardDev
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: AlexGirardDev
      revision: adv360-z3.2-2
      import: app/west.yml
    - name: zmk-auto-layer
      revision: main
      remote: urob
      path: modules/auto-layer
    - name: zmk-tri-state
      revision: main
      remote: urob
      path: modules/tri-state
  self:
    path: config
