name: Update File
on: [push, pull_request, workflow_dispatch]

#essentially every time i use the gui configurator it removes my references to turbos.dtsi so i just add it back 
jobs:
  update-file:
    runs-on: ubuntu-latest
    # Prevent running on pushes made by the GitHub Actions bot
    if: ${{ github.actor != 'github-actions[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Important to ensure history is available for push

      - name: Check and update file
        run: |
          FILE_PATH="config/adv360.keymap"
          if ! grep -q "turbos.dtsi" "$FILE_PATH"; then
            sed -i '/behaviors {/{N;N;s|#include "macros.dtsi"|#include "macros.dtsi"\n    #include "turbos.dtsi"|}' "$FILE_PATH"
            echo "File updated to include turbos.dtsi."
            
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add "$FILE_PATH"
            git commit -m "Add turbos.dtsi include to $FILE_PATH"
            git push
          else
            echo "File already contains turbos.dtsi."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
